name: Build MicroPython for STM32

on:
  workflow_dispatch:  # Allows manual trigger

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: |
          sudo apt update
          sudo apt install -y gcc-arm-none-eabi binutils-arm-none-eabi cmake make

      - name: Configure and Build
        run: |
          cd ports/stm32
          make submodules
          make BOARD=YOUR_BOARD

      - name: Check if Firmware Exists
        run: |
          if [ ! -f "ports/stm32/build-YOUR_BOARD/firmware.bin" ]; then
            echo "Error: firmware.bin not found!"
            exit 1
          fi

      - name: Upload Firmware Artifact
        uses: actions/upload-artifact@v4
        with:
          name: firmware-bin
          path: ports/stm32/build-YOUR_BOARD/firmware.bin
